// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjqtgearnshqhcgqonxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqcXRnZWFybnNocWhjZ3FvbnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzM2OTEsImV4cCI6MjA2NTE0OTY5MX0.HWQnDYW_zBPGTLtiYyaifgQ7si5NktEnqa2G3ztLx2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);